env:
  _target_: gymnasium.make
  render_mode: "human"
model:
  hidden_dim: 512
  in_dim: ${model_config.in_dim}
  out_dim: ${model_config.out_dim}
  _target_: ${model_config.model_path}
  device: ${device}
data_miner:
  _target_: core.dataminer.SimpleDataMiner
  alpha: 0.8
  gamma: 0.95
  model: ${model}
  env: ${env}
  batch_size: 64
  device: ${device}
  eval_seeds: [424240, 424241, 424242, 424243, 424244, 424245, 424246, 424247, 424248, 424249, 424250]

device: cpu