hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-0
  sweep:
    dir: outputs/${now:%Y-%m-%d}
    subdir: ${now:%H-%M-%S}-${hydra.job.num}

logger:
  _target_: logger.tensorboard.TensorBoardLogger
  log_dir: ${hydra:runtime.output_dir}
scheduler:
  _target_: core.scheduler.CosineAnnealingWarmupLR
  T_max: ${num_pseudo_epochs}
  eta_min: 1e-6
  optimizer: ${trainer.optimizer}
  warmup_steps: 5
data_miner:
  eval_seeds: [424240, 424241, 424242, 424243, 424244, 424245, 424246, 424247, 424248, 424249, 424250]
  drop_last: true

seed: 42

tensorboard_port: 6006
streamlit_port: 8501
device: cpu
save_checkpoint: True
name: