# @package _global_
defaults:
  - /env: CartPole/default
  - /env/CartPole/model_config


model:
  hidden_dim: 512
  device: ${device}
  body_depth: 0
  head_depth: 2
  value_depth: 2
  _target_: model.base.AutoModel
data_miner:
  _target_: core.dataminer.StepsDataMiner
  gamma: 0.99
  alpha: 1
  model: ${model}
  env: ${env}
  batch_size: 64
  device: ${device}
  num_steps: 1000
trainer:
  _target_: core.trainer.ReinforceTrainer
  model: ${model}
  entropy_coef: 0.01
  optimizer:
    _target_: torch.optim.AdamW
    lr: 2e-5

seed: 42
num_pseudo_epochs: 100
eval_freq: 10
device: cpu