# @package _global_

env:
  id: "CartPole-v1"
  _target_: gymnasium.make_vec
  num_envs: 8
  vectorization_mode: async
model:
  _target_: model.base.AutoModel
  head:
    _target_: model.head.DiscreteHead
    input_dim: 4
    hidden_dim: 32
    output_dim: 2
    activation: Tanh
    depth: 2
data_miner:
  gamma: 0.99
  alpha: 1
  batch_size: 256
  num_steps: 512
  _target_: core.dataminer.ClassicDataMiner
trainer:
  _target_: core.trainer.ReinforceTrainer
  optimizer:
    lr: 1e-4
  entropy_coef: 0

num_pseudo_epochs: 200
eval_freq: 10