# @package _global_

env:
  id: "InvertedPendulum-v5"
  _target_: gymnasium.make_vec
  num_envs: 8
  vectorization_mode: async
model:
  _target_: model.base.AutoModel
  head:
    _target_: model.head.ContinuosHead
    input_dim: 4
    hidden_dim: 16
    output_dim: 1
    activation: Tanh
    depth: 1
data_miner:
  gamma: 0.99
  alpha: 1
  batch_size: 256
  num_steps: 512
  _target_: core.dataminer.ClassicDataMiner
trainer:
  _target_: core.trainer.ReinforceTrainer
  optimizer:
    lr: 1e-4
  entropy_coef: 0
  # value_coef: 0.2

num_pseudo_epochs: 500
eval_freq: 10