# @package _global_
defaults:
  - /env: IsaacGym

env:
  task: BallBalance
  num_envs: 512
model:
  hidden_dim: 128
  # body:
  #   _target_: common.utils.build_mlp
  #   input_dim: 60
  #   hidden_dim: ${model.hidden_dim}
  #   depth: 4
  #   activation: Tanh
  head:
    _target_: model.head.ContinuosHead
    input_dim: 24
    hidden_dim: ${model.hidden_dim}
    output_dim: 3
    activation: ELU
    depth: 2
  value:
    _target_: common.utils.build_mlp
    input_dim: 24
    hidden_dim: ${model.hidden_dim}
    output_dim: 1
    depth: 3
    activation: ELU
data_miner:
  gamma: 0.99
  alpha: 0.95
  batch_size: 4096
  num_steps: 512
  _target_: core.dataminer.IsaacDataMiner
trainer:
  _target_: core.trainer.PPOTrainer
  accum_steps: 32
  optimizer:
    lr: 1e-4
  entropy_coef: 0.01
  value_coef: 1

num_pseudo_epochs: 500
eval_freq: 10