# @package _global_
defaults:
  - /env: IsaacGym

env:
  task: Cartpole
  num_envs: 8
model:
  _target_: model.base.AutoModel
  head:
    _target_: model.head.ContinuosHead
    input_dim: 4
    hidden_dim: 16
    output_dim: 1
    activation: Tanh
    depth: 1
data_miner:
  gamma: 0.99
  alpha: 1
  batch_size: 256
  num_steps: 512
  _target_: core.dataminer.IsaacDataMiner
trainer:
  _target_: core.trainer.ReinforceTrainer
  optimizer:
    lr: 1e-4
  entropy_coef: 0

num_pseudo_epochs: 500
eval_freq: 10