# @package _global_
defaults:
  - /env/LunarLander/model_config
  - /env: LunarLander/default


model:
  hidden_dim: 512
  body_depth: 2
  head_depth: 1
  value_depth: 1
data_miner:
  gamma: 0.99
  alpha: 0.9
  batch_size: 64
  num_steps: 1000
trainer:
  _target_: core.trainer.A2CTrainer
  value_coef: 1
  optimizer:
    lr: 3e-5

num_pseudo_epochs: 800
eval_freq: 10