# @package _global_
defaults:
  - /env/MountainCar@model_config: model_config
  - /env: MountainCar/default


model:
  hidden_dim: 512
  in_dim: ${model_config.in_dim}
  out_dim: ${model_config.out_dim}
  _target_: ${model_config.model_path}
  device: ${device}
data_miner:
  _target_: core.dataminer.StepsDataMiner
  gamma: 0.99
  alpha: 0.9
  model: ${model}
  env: ${env}
  batch_size: 64
  device: ${device}
  num_steps: 1000
  drop_last: true
  eval_seeds: [424240, 424241, 424242, 424243, 424244, 424245, 424246, 424247, 424248, 424249, 424250]
trainer:
  _target_: core.trainer.ValueReinforceTrainer
  model: ${model}
  value_coef: 1
  entropy: true
  entropy_coef: 0.01
  optimizer:
    _target_: torch.optim.AdamW
    lr: 3e-5
scheduler:
  _target_: core.scheduler.CosineAnnealingWarmupLR
  T_max: ${num_pseudo_epochs}
  eta_min: 1e-6
  optimizer: ${trainer.optimizer}
  warmup_steps: 5

seed: 43
num_pseudo_epochs: 500
eval_freq: 10
device: cpu
name: